[package]
name = "cys431_pex1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
bitvector = "0.1.5"
itertools = "0.12.1"
rug = "1.24.0"
